spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gift?autoReconnect=true
    username: root
    password: QazWsx123.
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.internal.NoCachingRegionFactory
management:
  endpoints:
    web:
      exposure:
        include: "*"